apiVersion: v1
kind: ConfigMap
metadata:
  name: bmi-config
  namespace: production
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "bmidb"
  FRONTEND_URL: "http://bmi-tracker.local"
